# Generated by Django 3.0.3 on 2020-08-25 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200825_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Status',
            new_name='status',
        ),
    ]
